const UPDATE_SUMMARY = "EDIT_SUMMARY";
const UPDATE_SKILL = "UPDATE_SKILL";
const UPDATE_GITHUB = "UPDATE_GITHUB";
const UPDATE_PROFILE_INFO = "UPDATE_PROFILE_INFO";
const UPDATE_DP = "UPDATE_DP";
const UPDATE_COVER = "UPDATE_COVER";
export {
  UPDATE_SUMMARY,
  UPDATE_SKILL,
  UPDATE_GITHUB,
  UPDATE_PROFILE_INFO,
  UPDATE_DP,
  UPDATE_COVER,
};
