const UPDATE_SUMMARY = "EDIT_SUMMARY";
const UPDATE_SKILL = "UPDATE_SKILL";
const UPDATE_GITHUB = "UPDATE_GITHUB";
const UPDATE_PROFILE = "UPDATE_PROFILE";

export { UPDATE_SUMMARY, UPDATE_SKILL, UPDATE_GITHUB, UPDATE_PROFILE };
